'use strict';
// Seed already-declared approval fixture identities using disposable local bytes.
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const Store=require('../../src/media/media-asset-store'),Assets=require('../../src/media/media-assets');
function seed(dir,project){const rows=[];
function walk(folder){for(const entry of fs.readdirSync(folder,{withFileTypes:true})){const file=path.join(folder,entry.name);if(entry.isDirectory()){walk(file);continue;}if(!/\.(png|mp4)$/.test(entry.name))continue;const rel=path.relative(dir,file).replace(/\\/g,'/'),st=fs.statSync(file);rows.push({assetId:'asset-'+crypto.createHash('sha256').update(rel).digest('hex').slice(0,32),contentHash:null,hashState:'unhashed',scope:{},mediaType:entry.name.endsWith('.mp4')?'video':'image',role:'import',source:'imported',lifecycle:'candidate',storage:{path:rel,bytes:st.size,mtimeMs:st.mtimeMs},legacy:{},indexedAt:'2026-09-16T00:00:00Z'});}}walk(dir);
for(const r of project.productionAuthority?.receipts||[]){let edge,rel;const shot=project.shots?.find(s=>s.id===r.shotId);if(r.kind==='entity-state'){const entity=project[r.list]?.find(e=>e.id===r.entityId);edge=entity?.continuityStates?.find(s=>s.id===r.stateId)||entity;rel=({characters:'anchors',locations:'plates',props:'props',vehicles:'vehicles'})[r.list]+'/'+r.value;}else{edge=r.kind==='shot-frame'?shot?.keyframes.find(f=>f.id===r.frameId):r.kind==='shot-motion'?shot?.clips.find(c=>c.id===r.unitKey):shot;rel='shots/'+r.shotId+'/takes/'+r.value;}const asset=rows.find(a=>a.storage.path===rel);if(!asset||!edge)throw Error('Fixture approval has no exact original: '+r.targetKey);r.assetId=asset.assetId;if(r.kind==='entity-state'){edge.approvedAssetId=asset.assetId;const e=project[r.list].find(e=>e.id===r.entityId);if(e.approvedFile===r.value)e.approvedAssetId=asset.assetId;}else if(r.kind==='shot-frame')edge.winnerAssetId=asset.assetId;else if(r.kind==='shot-motion')edge.videoWinnerAssetId=asset.assetId;else{edge.finalStillAssetId=asset.assetId;if(edge.creationBrief)edge.creationBrief.finalStillAssetId=asset.assetId;}}
Store.writeLedgerSync(dir,{schemaVersion:Assets.MEDIA_ASSETS_SCHEMA_VERSION,assets:rows});return project;}
module.exports={seed};
